# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

description = "a one page site for gohugo.io tweaked and ported from the hugo-highlights-theme"
features = [
	"onepage",
	"one page",
	"multi-language",
	"contact form",
	"google analytics",
]

homepage = ""
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/schmanat/hugo-highlights-theme/blob/master/LICENSE.md"
min_version = 0.15
name = "WD Theme"
tags = [
	"portfolio",
	"onepage",
	"one page",
	"contact form",
	"google analytics",
]

[author]
	homepage = "//wastlund.net"
	name = "Patrik Wästlund"

# If porting an existing theme
[original]
	homepage = "//html5up.net/highlights"
	name = "HTML5UP - Highlights"
	repo = "https://github.com/schmanat/hugo-highlights-theme/"
